#!/usr/bin/env bash
#
# bench/run.sh — reproducible end-to-end performance benchmark for spell.mbt.
#
# One command produces every number in the `## Performance` section of README.mbt.md
# and every table in bench/README.md:
#
#   bash bench/run.sh
#
# What it measures
# ----------------
#   [1] The dictionary source (fetched at run time, NEVER vendored).
#   [2] The documented `moon run cmd/main -- check ...` path on the real en_US
#       dictionary: process start / dictionary load / per-word checking, separated
#       by timing three points (no-arg, empty word list, N words) and taking medians.
#   [3] Head-to-head against the system `hunspell` binary when one is installed.
#       This is BINARY vs BINARY: our `moon build --target native --release`
#       executable against the native hunspell, same `.aff`/`.dic`, same word list.
#   [4] A scaling curve on SYNTHETIC `.aff`/`.dic` pairs (1k / 10k / 50k / 200k
#       entries, fixed affix shape) generated by bench/gen_dict.sh.
#   [5] Release artifact sizes (wasm / wasm-gc / js / native).
#
# Honesty rules this script follows
# ---------------------------------
#   * Every number is measured here; nothing is hard-coded or estimated.
#   * Times are wall-clock medians over several repetitions (reps configurable).
#   * Nothing is fetched into the repository; the dictionary lives in a temp dir.
#   * If the network is unavailable the real-dictionary sections are SKIPPED with a
#     clear message and the synthetic + artifact sections still run. The script
#     still exits 0, because "no network" is not a benchmark failure.
#   * These are machine-specific end-to-end numbers. See bench/README.md.
#
# Environment overrides
# ---------------------
#   BENCH_REPS_SMALL=n     repetitions for start / load measurements   (default 9)
#   BENCH_REPS_BIG=n       repetitions for throughput measurements      (default 5)
#   BENCH_REPS_HUGE=n      repetitions for >=100k-word measurements     (default 3)
#   BENCH_SIZES="..."      synthetic dictionary sizes      (default "1000 10000 50000 200000")
#   BENCH_MAIN_WORDS=path  large word list              (default /usr/share/dict/words)
#   BENCH_FALLBACK_WORDS=n size of the generated fallback list          (default 200000)
#   BENCH_MEASURE_WORDS=n  words checked per synthetic size (see section 4) (default 100000)
#   BENCH_SKIP_REAL=1      skip the fetched real dictionary
#   BENCH_SKIP_HUNSPELL=1  skip the head-to-head
#   BENCH_KEEP_TEMP=1      keep the temp directory and print its path
#   BENCH_TMP=dir          scratch parent dir (a fresh subdir is created there and removed)
#
# Exit status: 0 when a report was produced, 1 on a real failure (the build or the
# CLI contract is broken).

set -uo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"
export PATH="$HOME/.moon/bin:$PATH"

REPS_SMALL="${BENCH_REPS_SMALL:-9}"
REPS_BIG="${BENCH_REPS_BIG:-5}"
REPS_HUGE="${BENCH_REPS_HUGE:-3}"
SIZES="${BENCH_SIZES:-1000 10000 50000 200000}"
MAIN_WORDS="${BENCH_MAIN_WORDS:-/usr/share/dict/words}"
FALLBACK_WORDS="${BENCH_FALLBACK_WORDS:-200000}"
MEASURE_WORDS="${BENCH_MEASURE_WORDS:-100000}"
KEEP_TEMP="${BENCH_KEEP_TEMP:-0}"
SKIP_REAL="${BENCH_SKIP_REAL:-0}"
SKIP_HUNSPELL="${BENCH_SKIP_HUNSPELL:-0}"
HUGE_THRESHOLD=100000

DICT_AFF_URL="https://cdn.jsdelivr.net/gh/LibreOffice/dictionaries@master/en/en_US.aff"
DICT_DIC_URL="https://cdn.jsdelivr.net/gh/LibreOffice/dictionaries@master/en/en_US.dic"
DICT_RDM_URL="https://cdn.jsdelivr.net/gh/LibreOffice/dictionaries@master/en/README_en_US.txt"

# ------------------------------------------------------------------ small helpers

TIMEFORMAT='%6R'
TAB="$(printf '\t')"

hr() { printf -- '--------------------------------------------------------------------------------\n'; }
section() { echo; hr; echo "== $1"; hr; }
have() { command -v "$1" >/dev/null 2>&1; }

median() {
  sort -n | awk '{a[NR]=$1} END{
    if (NR == 0) { print ""; exit }
    if (NR % 2) printf "%.4f\n", a[(NR + 1) / 2]
    else printf "%.4f\n", (a[NR / 2] + a[NR / 2 + 1]) / 2
  }'
}

# timed <reps> <cmd...>  -> median wall-clock seconds on stdout (4 dp).
# A non-zero exit is a hard error unless TIMED_ALLOWED_RC names that exact code
# (the no-argument run prints usage and exits 2 by design).
timed() {
  local reps="$1"; shift
  local allowed="${TIMED_ALLOWED_RC:-0}"
  local i t rc acc=""
  for ((i = 0; i < reps; i++)); do
    t=$( { time "$@" >/dev/null 2>&1; } 2>&1 ); rc=$?
    if [ "$rc" -ne 0 ] && [ "$rc" -ne "$allowed" ]; then
      echo "ERROR: command failed (exit $rc): $*" >&2
      return 1
    fi
    acc="$acc$t"$'\n'
  done
  printf '%s' "$acc" | median
}

# Float formatting (awk, so this works with the system bash 3.2 on macOS).
f_s()     { awk -v x="${1:-0}" 'BEGIN{printf "%.4f", x + 0}'; }
f_ms()    { awk -v x="${1:-0}" 'BEGIN{printf "%.2f", (x + 0) * 1000}'; }
f_us()    { awk -v t="${1:-0}" -v n="${2:-0}" 'BEGIN{ if (n <= 0) printf "n/a"; else printf "%.2f", 1e6 * t / n }'; }
f_wps()   { awk -v n="${1:-0}" -v t="${2:-0}" 'BEGIN{ if (t <= 0) printf "n/a"; else printf "%.0f", n / t }'; }
f_ratio() { awk -v a="${1:-0}" -v b="${2:-0}" 'BEGIN{ if (b <= 0) printf "n/a"; else printf "%.2fx", a / b }'; }
f_pct()   { awk -v a="${1:-0}" -v b="${2:-0}" 'BEGIN{ if (b <= 0) printf "n/a"; else printf "%.1f%%", 100 * a / b }'; }
f_sub()   { awk -v a="${1:-0}" -v b="${2:-0}" 'BEGIN{printf "%.6f", a - b}'; }
f_gib()   { awk -v b="${1:-0}" 'BEGIN{ if (b <= 0) printf "?"; else printf "%.0f GiB", b / 1073741824}'; }

# Number of non-empty lines in a file.
word_count() { grep -c . "$1" 2>/dev/null | tr -d ' '; }

# The `hunspell -d` spelling of a dictionary whose files are <dir>/<base>.aff/.dic.
hun_d() { printf '%s/%s' "$(dirname "$1")" "$(basename "$1" .dic)"; }

# Verdicts for one word per line: 1 = accepted, 0 = rejected. Only the two
# engines that answer per word are supported here (hunspell lists misses only).
verdicts() { # <engine> <aff> <dic> <wordlist>
  local engine="$1" aff="$2" dic="$3" words="$4"
  case "$engine" in
    native) "$NATIVE" check --aff "$aff" --dic "$dic" --words "$words" 2>/dev/null ;;
    moon)   moon run cmd/main -- check --aff "$aff" --dic "$dic" --words "$words" 2>/dev/null ;;
  esac
}

# ------------------------------------------------------------- scratch directory

if [ -n "${BENCH_TMP:-}" ]; then
  mkdir -p "$BENCH_TMP" || { echo "ERROR: cannot create BENCH_TMP=$BENCH_TMP" >&2; exit 1; }
  TMP="$(mktemp -d "$BENCH_TMP/spell-bench.XXXXXX")"
  CLEANUP=1
else
  TMP="$(mktemp -d)"
  CLEANUP=1
fi
if [ "$KEEP_TEMP" = "1" ]; then CLEANUP=0; fi
cleanup() { [ "$CLEANUP" = "1" ] && rm -rf "$TMP"; }
trap cleanup EXIT

EMPTY_FILE="$TMP/empty-words.txt"
: > "$EMPTY_FILE"
ONE_FILE="$TMP/one-word.txt"
printf 'hello\n' > "$ONE_FILE"

NATIVE="$REPO_ROOT/_build/native/release/build/cmd/main/main.exe"
WASM_ART="$REPO_ROOT/_build/wasm/release/build/cmd/main/main.wasm"
WASMGC_ART="$REPO_ROOT/_build/wasm-gc/release/build/cmd/main/main.wasm"
JS_ART="$REPO_ROOT/_build/js/release/build/cmd/main/main.js"

# Globals (initialised so `set -u` is happy even when a section is skipped).
E_START=""; E_EMPTY=""; E_WORDS=""
MOON_START=""; MOON_EMPTY=""; MOON_ONE=""; MOON_N=""; MOON_BIG=""
MREL_START=""; MREL_EMPTY=""; MREL_ONE=""; MREL_N=""; MOONREL_BIG=""
HAVE_REAL=0
AFF=""; DIC=""; ENTRIES=""
N_ENTRIES="0"; N_ENTRIES_DECLARED="0"
ONLY_FLAG=""; RULE_LINES="?"; RULE_BLOCKS="?"

engine_start() { # <engine> <reps>
  local engine="$1" reps="$2"
  case "$engine" in
    native)   E_START="$(TIMED_ALLOWED_RC=2 timed "$reps" "$NATIVE")" ;;
    moon)     E_START="$(TIMED_ALLOWED_RC=2 timed "$reps" moon run cmd/main)" ;;
    moonrel)  E_START="$(TIMED_ALLOWED_RC=2 timed "$reps" moon run --release cmd/main)" ;;
    hunspell) E_START="$(timed "$reps" hunspell -v)" ;;
  esac
}

engine_empty() { # <engine> <aff> <dic> <reps>
  local engine="$1" aff="$2" dic="$3" reps="$4"
  case "$engine" in
    native)   E_EMPTY="$(timed "$reps" "$NATIVE" check --aff "$aff" --dic "$dic" --words "$EMPTY_FILE")" ;;
    moon)     E_EMPTY="$(timed "$reps" moon run cmd/main -- check --aff "$aff" --dic "$dic" --words "$EMPTY_FILE")" ;;
    moonrel)  E_EMPTY="$(timed "$reps" moon run --release cmd/main -- check --aff "$aff" --dic "$dic" --words "$EMPTY_FILE")" ;;
    hunspell) E_EMPTY="$(timed "$reps" hunspell -d "$(hun_d "$dic")" -l "$EMPTY_FILE")" ;;
  esac
}

engine_words() { # <engine> <aff> <dic> <wordlist> <reps>
  local engine="$1" aff="$2" dic="$3" words="$4" reps="$5"
  case "$engine" in
    native)   E_WORDS="$(timed "$reps" "$NATIVE" check --aff "$aff" --dic "$dic" --words "$words")" ;;
    moon)     E_WORDS="$(timed "$reps" moon run cmd/main -- check --aff "$aff" --dic "$dic" --words "$words")" ;;
    moonrel)  E_WORDS="$(timed "$reps" moon run --release cmd/main -- check --aff "$aff" --dic "$dic" --words "$words")" ;;
    hunspell) E_WORDS="$(timed "$reps" hunspell -d "$(hun_d "$dic")" -l "$words")" ;;
  esac
}

# ------------------------------------------------------------------ 0. environment

echo "spell.mbt — reproducible performance benchmark"
hr
echo "date         : $(date -u '+%Y-%m-%dT%H:%M:%SZ')  (UTC; all times below are wall-clock medians)"
echo "host         : $(hostname 2>/dev/null || echo '?')"
OS_VERSION=""
if have sw_vers; then
  OS_VERSION="macOS $(sw_vers -productVersion 2>/dev/null) ($(sw_vers -buildVersion 2>/dev/null))"
  echo "os           : $OS_VERSION $(uname -m), kernel $(uname -r)"
else
  echo "os           : $(uname -s) $(uname -r) $(uname -m)"
fi
CPU="$(sysctl -n machdep.cpu.brand_string 2>/dev/null || true)"
if [ -z "$CPU" ] && [ -r /proc/cpuinfo ]; then
  CPU="$(awk -F: '/^model name/ { sub(/^ +/, "", $2); print $2; exit }' /proc/cpuinfo)"
fi
CORES="$(sysctl -n hw.ncpu 2>/dev/null || nproc 2>/dev/null || echo '?')"
echo "cpu          : ${CPU:-?} (${CORES} cores)"
MEM="$(sysctl -n hw.memsize 2>/dev/null || true)"
if [ -z "$MEM" ] && [ -r /proc/meminfo ]; then
  MEM="$(awk '/^MemTotal:/ { print $2 * 1024; exit }' /proc/meminfo)"
fi
echo "memory       : $(f_gib "${MEM:-0}")"
MOON_ALL="$(moon version --all 2>/dev/null || true)"
if [ -n "$MOON_ALL" ]; then
  printf '%s\n' "$MOON_ALL" | grep -E '^(moon|moonc|moonrun) ' | sed 's/^/toolchain    : /'
else
  echo "toolchain    : moon NOT FOUND on PATH ($HOME/.moon/bin)"
fi
echo "repetitions  : start/load ${REPS_SMALL}, throughput ${REPS_BIG}, >=${HUGE_THRESHOLD} words ${REPS_HUGE}"
echo "scratch dir  : $TMP"

HUNSPELL=""
if [ "$SKIP_HUNSPELL" = "1" ]; then
  echo "hunspell     : skipped (BENCH_SKIP_HUNSPELL=1)"
elif have hunspell; then
  HUNSPELL="$(hunspell -v 2>&1 | grep -o 'Hunspell [0-9][0-9.]*' | head -1)"
  [ -n "$HUNSPELL" ] || HUNSPELL="hunspell (version string unparsed)"
  echo "hunspell     : $HUNSPELL at $(command -v hunspell)"
else
  echo "hunspell     : not found — the head-to-head will be skipped"
fi

# -------------------------------------------------------------- build the CLI

section "build (release, all four backends)"
build_target() { # <target>
  local target="$1" label="$2"
  if moon build --target "$target" --release >/dev/null 2>&1; then
    printf '  moon build --release --target %-8s ok (%s)\n' "$target" "$label"
  else
    printf '  moon build --release --target %-8s FAILED\n' "$target"
  fi
}
build_target wasm "wasm"
build_target wasm-gc "wasm-gc"
build_target js "js"
build_target native "native"

# Verify the CLI contract before trusting any number (same probe as conformance/run.sh).
# This first `moon run` also warms the debug build that section 2 times.
PROBE="$TMP/probe"
mkdir -p "$PROBE"
printf 'SET UTF-8\n' > "$PROBE/probe.aff"
printf '2\nhello\nworld\n' > "$PROBE/probe.dic"
printf 'hello\nzzzz\n' > "$PROBE/probe.words"
PROBE_OUT="$(moon run cmd/main -- check --aff "$PROBE/probe.aff" --dic "$PROBE/probe.dic" --words "$PROBE/probe.words" 2>/dev/null)"
if [ "$PROBE_OUT" = "$(printf '1\n0')" ]; then
  echo "  CLI contract ok ('hello' -> 1, 'zzzz' -> 0)"
else
  echo "ERROR: the 'check' CLI does not follow the conformance contract; no timing is meaningful." >&2
  echo "       Got: $(printf '%s' "$PROBE_OUT" | tr '\n' ' ')" >&2
  exit 1
fi

if [ ! -x "$NATIVE" ]; then
  echo "WARNING: native release executable not found at $NATIVE" >&2
  echo "         native-backed sections (head-to-head, scaling) will be skipped." >&2
fi

# --------------------------------------------------------- 1. dictionary source

section "1. dictionary source (fetched at run time; never vendored)"
if [ "$SKIP_REAL" = "1" ]; then
  echo "SKIPPED: BENCH_SKIP_REAL=1"
elif ! have curl; then
  echo "SKIPPED: curl is not available, so the real dictionary cannot be fetched."
else
  echo "fetching en_US (.aff/.dic) from jsDelivr ..."
  fetch_retries() { # <url> <out>
    local url="$1" out="$2" attempt
    for attempt in 1 2 3; do
      if curl -fsSL --max-time 120 -o "$out" "$url" 2>/dev/null; then return 0; fi
      sleep 3
    done
    return 1
  }
  if fetch_retries "$DICT_AFF_URL" "$TMP/en_US.aff" && fetch_retries "$DICT_DIC_URL" "$TMP/en_US.dic"; then
    HAVE_REAL=1
    AFF="$TMP/en_US.aff"
    DIC="$TMP/en_US.dic"
    curl -fsSL --max-time 60 -o "$TMP/README_en_US.txt" "$DICT_RDM_URL" 2>/dev/null || true
  else
    echo "SKIPPED: could not fetch the dictionary (network unavailable)."
    echo "         The synthetic scaling curve and the artifact sizes below do not need it."
  fi
fi

if [ "$HAVE_REAL" = "1" ]; then
  ENTRIES="$TMP/en_US.entries.txt"
  # Strip the `/flags` field. (SCOWL's en_US has no escaped `\/` inside a word;
  # the benchmark records that assumption rather than pretending to handle it.)
  awk 'NR > 1 { sub(/\/.*$/, ""); if ($0 != "") print }' "$DIC" > "$ENTRIES"
  N_ENTRIES="$(word_count "$ENTRIES")"
  N_ENTRIES_DECLARED="$(head -1 "$DIC" | tr -dc '0-9')"
  AFF_SHA="$(shasum -a 256 "$AFF" 2>/dev/null | awk '{print $1}')"
  DIC_SHA="$(shasum -a 256 "$DIC" 2>/dev/null | awk '{print $1}')"
  AFF_HEADER="$(sed -n '1p' "$AFF")"
  ONLY_FLAG="$(awk '$1 == "ONLYINCOMPOUND" { print $2; exit }' "$AFF")"
  RULE_LINES="$(awk '$1 == "PFX" || $1 == "SFX" { if ($3 != "Y" && $3 != "N") n++ } END { print n + 0 }' "$AFF")"
  RULE_BLOCKS="$(awk '$1 == "PFX" || $1 == "SFX" { print $2 }' "$AFF" | sort -u | wc -l | tr -d ' ')"
  RDM_VERSION="$(awk -F': ' '/^Version /{print $2; exit}' "$TMP/README_en_US.txt" 2>/dev/null || true)"
  echo
  echo "  .aff url        : $DICT_AFF_URL"
  echo "  .dic url        : $DICT_DIC_URL"
  echo "  fetched into    : $TMP  (temp dir; NOT written into the repository)"
  echo "  in-file header  : $AFF_HEADER"
  if [ -n "$RDM_VERSION" ]; then echo "  upstream README : Version $RDM_VERSION (SCOWL size 60)"; fi
  echo "  entries         : $N_ENTRIES (declared count in .dic line 1: ${N_ENTRIES_DECLARED:-?})"
  echo "  affix rules     : $RULE_LINES rules in $RULE_BLOCKS blocks (PFX/SFX)"
  echo "  sha256 .aff     : $AFF_SHA"
  echo "  sha256 .dic     : $DIC_SHA"
  echo "  licence         : SCOWL / Kevin Atkinson permissive notice, plus the Ispell BSD"
  echo "                    licence and the WordNet notice for parts of the sources;"
  echo "                    distributed by the LibreOffice dictionaries project."
  echo "                    Full notice: $DICT_RDM_URL"
  echo "                    Read at run time and never redistributed with this repo."
fi

# ----------------------------------------------------- 2. real dictionary, wasm

section "2. real dictionary with the wasm backend — load vs check"
if [ "$HAVE_REAL" != "1" ]; then
  echo "SKIPPED: the real dictionary is not available (see section 1)."
else
  echo "the README documents \`moon run cmd/main -- check ...\`, whose default is DEBUG wasm."
  echo "The same backend built with --release is reported next to it (both are wasm; the"
  echo "release column is what the 0.15 s / 3.8 s figures in the project notes came from)."
  echo "word list for the check measurement: the dictionary's own $N_ENTRIES entries (direct hits)."
  echo
  engine_start moon "$REPS_SMALL"; MOON_START="$E_START"
  engine_empty moon "$AFF" "$DIC" "$REPS_SMALL"; MOON_EMPTY="$E_EMPTY"
  engine_words moon "$AFF" "$DIC" "$ONE_FILE" "$REPS_SMALL"; MOON_ONE="$E_WORDS"
  engine_words moon "$AFF" "$DIC" "$ENTRIES" "$REPS_BIG"; MOON_N="$E_WORDS"
  engine_start moonrel "$REPS_SMALL"; MREL_START="$E_START"
  engine_empty moonrel "$AFF" "$DIC" "$REPS_SMALL"; MREL_EMPTY="$E_EMPTY"
  engine_words moonrel "$AFF" "$DIC" "$ONE_FILE" "$REPS_SMALL"; MREL_ONE="$E_WORDS"
  engine_words moonrel "$AFF" "$DIC" "$ENTRIES" "$REPS_BIG"; MREL_N="$E_WORDS"

  if [ -z "$MOON_START" ] || [ -z "$MOON_EMPTY" ] || [ -z "$MOON_N" ] ||
     [ -z "$MREL_START" ] || [ -z "$MREL_EMPTY" ] || [ -z "$MREL_N" ]; then
    echo "ERROR: a timed wasm measurement failed; see the messages above." >&2
  else
    MOON_LOAD="$(f_sub "$MOON_EMPTY" "$MOON_START")"
    MOON_CHECK="$(f_sub "$MOON_N" "$MOON_EMPTY")"
    MREL_LOAD="$(f_sub "$MREL_EMPTY" "$MREL_START")"
    MREL_CHECK="$(f_sub "$MREL_N" "$MREL_EMPTY")"
    # The 2-point cross-check suggested by the benchmark brief: a 1-word run minus
    # process start minus one word of checking.
    two_point() { # <one-run> <start> <check-only> -> load estimate
      awk -v t1="$1" -v t0="$2" -v t="$3" -v n="$N_ENTRIES" \
        'BEGIN{ printf "%.4f", t1 - t0 - (n > 0 ? t / n : 0) }'
    }
    MOON_LOAD_2PT="$(two_point "$MOON_ONE" "$MOON_START" "$MOON_CHECK")"
    MREL_LOAD_2PT="$(two_point "$MREL_ONE" "$MREL_START" "$MREL_CHECK")"
    printf '  %-46s %12s %13s\n' "metric" "wasm debug" "wasm release"
    printf '  %-46s %12s %13s\n' "process start (no-arg run, exits 2)" "$MOON_START" "$MREL_START"
    printf '  %-46s %12s %13s\n' "start + load (empty word list)" "$MOON_EMPTY" "$MREL_EMPTY"
    printf '  %-46s %12s %13s\n' "  => load only (derived)" "$(f_s "$MOON_LOAD")" "$(f_s "$MREL_LOAD")"
    printf '  %-46s %12s %13s\n' "1-word run (cross-check point)" "$MOON_ONE" "$MREL_ONE"
    printf '  %-46s %12s %13s\n' "$N_ENTRIES-word run, all hits" "$MOON_N" "$MREL_N"
    printf '  %-46s %12s %13s\n' "  => checking only (derived)" "$(f_s "$MOON_CHECK")" "$(f_s "$MREL_CHECK")"
    printf '  %-46s %12s %13s\n' "per-word checking cost (µs/word)" "$(f_us "$MOON_CHECK" "$N_ENTRIES")" "$(f_us "$MREL_CHECK" "$N_ENTRIES")"
    printf '  %-46s %12s %13s\n' "throughput, end-to-end (words/s)" "$(f_wps "$N_ENTRIES" "$MOON_N")" "$(f_wps "$N_ENTRIES" "$MREL_N")"
    printf '  %-46s %12s %13s\n' "throughput, checking only (words/s)" "$(f_wps "$N_ENTRIES" "$MOON_CHECK")" "$(f_wps "$N_ENTRIES" "$MREL_CHECK")"
    echo
    echo "  cross-check of the 2-point method (1-word run minus start minus 1 word):"
    echo "    debug   load ≈ $(f_s "$MOON_LOAD_2PT") s  vs  $(f_s "$MOON_LOAD") s from the empty-word-list run"
    echo "    release load ≈ $(f_s "$MREL_LOAD_2PT") s  vs  $(f_s "$MREL_LOAD") s from the empty-word-list run"
    echo "  (the empty-word-list point is used in the table because it is a single"
    echo "   measurement, so process-start noise enters only once)"

    # Correctness self-check: every entry must be accepted, except entries that
    # carry ONLYINCOMPOUND (which Hunspell also rejects standalone).
    VERD="$TMP/en_US.verdicts.txt"
    verdicts native "$AFF" "$DIC" "$ENTRIES" > "$VERD"
    REJ="$TMP/en_US.rejected.txt"
    paste -d "$TAB" "$ENTRIES" "$VERD" | awk -F'\t' '$2 == 0 { print $1 }' > "$REJ"
    N_REJ="$(word_count "$REJ")"
    echo
    echo "  self-check (native): accepted $((N_ENTRIES - N_REJ))/$N_ENTRIES entries; rejected $N_REJ"
    if [ "$N_REJ" -gt 0 ]; then
      awk -F/ 'NR > 1 { print $1 "\t" (NF > 1 ? substr($0, index($0, "/") + 1) : "") }' "$DIC" |
        sort > "$TMP/en_US.flags.tsv"
      N_EXPLAINED=0
      if [ -n "$ONLY_FLAG" ]; then
        N_EXPLAINED="$(sort "$REJ" | join -t "$TAB" - "$TMP/en_US.flags.tsv" |
          awk -F'\t' -v o="$ONLY_FLAG" 'index($2, o) > 0' | word_count /dev/stdin)"
      fi
      if [ "$N_EXPLAINED" = "$N_REJ" ]; then
        echo "    all $N_REJ carry the .aff ONLYINCOMPOUND flag '$ONLY_FLAG' — correct standalone rejection"
      else
        echo "    $N_EXPLAINED/$N_REJ explained by ONLYINCOMPOUND '$ONLY_FLAG'; the rest:"
        sort "$REJ" | join -t "$TAB" - "$TMP/en_US.flags.tsv" |
          awk -F'\t' -v o="$ONLY_FLAG" 'index($2, o) == 0 { print "      " $1 " [flags: " $2 "]" }'
      fi
      echo "    rejected words: $(tr '\n' ' ' < "$REJ")"
    else
      echo "    every entry is accepted standalone"
    fi
  fi
fi

# ------------------------------------------------- 3. head-to-head: native vs hunspell

section "3. head-to-head: native release binary vs system hunspell (same files)"
if [ "$HAVE_REAL" != "1" ]; then
  echo "SKIPPED: the real dictionary is not available (see section 1)."
elif [ ! -x "$NATIVE" ]; then
  echo "SKIPPED: our native release executable was not built."
else
  echo "ours  : $NATIVE"
  echo "        ($(wc -c < "$NATIVE" | tr -d ' ') bytes, \`moon build --target native --release\`)"
  if [ -n "$HUNSPELL" ]; then
    echo "theirs: $(command -v hunspell) ($HUNSPELL)"
  else
    echo "theirs: hunspell NOT available — comparison skipped (no number is fabricated)."
  fi

  # The big word list (or a generated fallback when the OS has none). The
  # fallback is a 50/50 hit/miss mix built from the real dictionary, so the row
  # still exercises both paths; its exact shape is printed with the result.
  BIG=""
  BIG_LABEL=""
  BIG_REPS="$REPS_HUGE"
  if [ -r "$MAIN_WORDS" ]; then
    BIG="$MAIN_WORDS"
    BIG_LABEL="$MAIN_WORDS"
  else
    BIG="$TMP/fallback-words.txt"
    awk -v want="$FALLBACK_WORDS" '
      NR > 1 { w[++n] = $1 }
      END {
        for (i = 0; i < want; i++) {
          word = w[(i % n) + 1]
          if (i % 2) print word "xq"; else print word
        }
      }' "$ENTRIES" > "$BIG"
    BIG_LABEL="$BIG (generated: $MAIN_WORDS not present; alternating dictionary word / word+\"xq\", so ~50% hits)"
  fi
  BIG_N="$(word_count "$BIG")"

  engine_start native "$REPS_SMALL"; NAT_START="$E_START"
  engine_empty native "$AFF" "$DIC" "$REPS_SMALL"; NAT_EMPTY="$E_EMPTY"
  engine_words native "$AFF" "$DIC" "$ENTRIES" "$REPS_BIG"; NAT_HIT="$E_WORDS"
  # A controlled all-miss list of the same size: every entry with "xq" appended.
  MISS="$TMP/misses-49568.txt"
  awk 'NF { print $0 "xq" }' "$ENTRIES" > "$MISS"
  engine_words native "$AFF" "$DIC" "$MISS" "$REPS_BIG"; NAT_MISS="$E_WORDS"
  engine_words native "$AFF" "$DIC" "$BIG" "$BIG_REPS"; NAT_BIG="$E_WORDS"

  if [ -n "$HUNSPELL" ]; then
    engine_start hunspell "$REPS_SMALL"; HUN_START="$E_START"
    engine_empty hunspell "$AFF" "$DIC" "$REPS_SMALL"; HUN_EMPTY="$E_EMPTY"
    engine_words hunspell "$AFF" "$DIC" "$ENTRIES" "$REPS_BIG"; HUN_HIT="$E_WORDS"
    engine_words hunspell "$AFF" "$DIC" "$MISS" "$REPS_BIG"; HUN_MISS="$E_WORDS"
    engine_words hunspell "$AFF" "$DIC" "$BIG" "$BIG_REPS"; HUN_BIG="$E_WORDS"
  fi

  # Never turn an empty measurement into a number: an unset result would be read
  # as 0 by the arithmetic below.
  if [ -z "$NAT_START" ] || [ -z "$NAT_EMPTY" ] || [ -z "$NAT_HIT" ] ||
     [ -z "$NAT_MISS" ] || [ -z "$NAT_BIG" ]; then
    echo "ERROR: a native measurement failed; section 3 is skipped." >&2
    NAT_START=""
  fi
  if [ -n "$HUNSPELL" ] && { [ -z "$HUN_START" ] || [ -z "$HUN_EMPTY" ] ||
     [ -z "$HUN_HIT" ] || [ -z "$HUN_MISS" ] || [ -z "$HUN_BIG" ]; }; then
    echo "WARNING: a hunspell measurement failed; the head-to-head is skipped." >&2
    HUNSPELL=""
  fi

  if [ -n "$NAT_START" ]; then
  NAT_LOAD="$(f_sub "$NAT_EMPTY" "$NAT_START")"
  NAT_HITONLY="$(f_sub "$NAT_HIT" "$NAT_EMPTY")"
  NAT_MISSONLY="$(f_sub "$NAT_MISS" "$NAT_EMPTY")"
  if [ -n "$HUNSPELL" ]; then
    HUN_LOAD="$(f_sub "$HUN_EMPTY" "$HUN_START")"
    HUN_HITONLY="$(f_sub "$HUN_HIT" "$HUN_EMPTY")"
    HUN_MISSONLY="$(f_sub "$HUN_MISS" "$HUN_EMPTY")"
  fi

  echo
  echo "times are medians over $REPS_SMALL (start/load), $REPS_BIG (49,568 words), $BIG_REPS ($BIG_N words) repetitions"
  echo
  if [ -n "$HUNSPELL" ]; then
    printf '  %-40s %14s %14s %10s\n' "metric" "ours native" "hunspell" "ratio"
    printf '  %-40s %14s %14s %10s\n' "process start (s)" "$NAT_START" "$HUN_START" "$(f_ratio "$NAT_START" "$HUN_START")"
    printf '  %-40s %14s %14s %10s\n' "start + load (s)" "$NAT_EMPTY" "$HUN_EMPTY" "$(f_ratio "$NAT_EMPTY" "$HUN_EMPTY")"
    printf '  %-40s %14s %14s %10s\n' "  load only (s)" "$(f_s "$NAT_LOAD")" "$(f_s "$HUN_LOAD")" "$(f_ratio "$NAT_LOAD" "$HUN_LOAD")"
    echo "  $N_ENTRIES words, all hits (the dictionary's own entries):"
    printf '  %-40s %14s %14s %10s\n' "  total (s)" "$NAT_HIT" "$HUN_HIT" "$(f_ratio "$NAT_HIT" "$HUN_HIT")"
    printf '  %-40s %14s %14s %10s\n' "  checking only (s)" "$(f_s "$NAT_HITONLY")" "$(f_s "$HUN_HITONLY")" "$(f_ratio "$NAT_HITONLY" "$HUN_HITONLY")"
    printf '  %-40s %14s %14s %10s\n' "  per word (µs)" "$(f_us "$NAT_HITONLY" "$N_ENTRIES")" "$(f_us "$HUN_HITONLY" "$N_ENTRIES")" "$(f_ratio "$(f_us "$NAT_HITONLY" "$N_ENTRIES")" "$(f_us "$HUN_HITONLY" "$N_ENTRIES")")"
    printf '  %-40s %14s %14s %10s\n' "  throughput (words/s, end-to-end)" "$(f_wps "$N_ENTRIES" "$NAT_HIT")" "$(f_wps "$N_ENTRIES" "$HUN_HIT")" ""
    echo "  $N_ENTRIES words, all misses (each entry + \"xq\"):"
    printf '  %-40s %14s %14s %10s\n' "  total (s)" "$NAT_MISS" "$HUN_MISS" "$(f_ratio "$NAT_MISS" "$HUN_MISS")"
    printf '  %-40s %14s %14s %10s\n' "  checking only (s)" "$(f_s "$NAT_MISSONLY")" "$(f_s "$HUN_MISSONLY")" "$(f_ratio "$NAT_MISSONLY" "$HUN_MISSONLY")"
    printf '  %-40s %14s %14s %10s\n' "  per word (µs)" "$(f_us "$NAT_MISSONLY" "$N_ENTRIES")" "$(f_us "$HUN_MISSONLY" "$N_ENTRIES")" "$(f_ratio "$(f_us "$NAT_MISSONLY" "$N_ENTRIES")" "$(f_us "$HUN_MISSONLY" "$N_ENTRIES")")"
    printf '  %-40s %14s %14s %10s\n' "  throughput (words/s, end-to-end)" "$(f_wps "$N_ENTRIES" "$NAT_MISS")" "$(f_wps "$N_ENTRIES" "$HUN_MISS")" ""
    echo "  $BIG_N words: $BIG_LABEL"
    printf '  %-40s %14s %14s %10s\n' "  total (s)" "$NAT_BIG" "$HUN_BIG" "$(f_ratio "$NAT_BIG" "$HUN_BIG")"
    printf '  %-40s %14s %14s %10s\n' "  throughput (words/s, end-to-end)" "$(f_wps "$BIG_N" "$NAT_BIG")" "$(f_wps "$BIG_N" "$HUN_BIG")" ""
  else
    printf '  %-40s %14s\n' "metric" "ours native"
    printf '  %-40s %14s\n' "process start (s)" "$NAT_START"
    printf '  %-40s %14s\n' "start + load (s)" "$NAT_EMPTY"
    printf '  %-40s %14s\n' "  load only (s)" "$(f_s "$NAT_LOAD")"
    printf '  %-40s %14s\n' "$N_ENTRIES all hits (s)" "$NAT_HIT"
    printf '  %-40s %14s\n' "$N_ENTRIES all misses (s)" "$NAT_MISS"
    printf '  %-40s %14s\n' "$BIG_N words (s)" "$NAT_BIG"
  fi

  # Hit ratio of the big list, so the reader can see why the two regimes differ.
  BIG_HITS="$(verdicts native "$AFF" "$DIC" "$BIG" | grep -c '^1$' | tr -d ' ')"
  echo
  echo "  hit ratio on the big list: $BIG_HITS/$BIG_N accepted = $(f_pct "$BIG_HITS" "$BIG_N")"
  echo "  (the miss path scans the whole affix-rule set; the hit path is one map access —"
  echo "   src/spell/lookup.mbt: direct_hit vs affix_hit)"

  # The all-miss list must really be all misses, or the row above is mislabelled.
  MISS_ACC="$(verdicts native "$AFF" "$DIC" "$MISS" | grep -c '^1$' | tr -d ' ')"
  echo "  all-miss list check: $MISS_ACC/$N_ENTRIES of the \"+xq\" words were accepted (expected 0)"

  # Correctness cross-check against hunspell on the dictionary's own entries.
  if [ -n "$HUNSPELL" ]; then
    echo
    echo "  correctness cross-check on the dictionary's own $N_ENTRIES entries:"
    OUR_REJ="$TMP/ours-rejected.txt"
    HUN_REJ="$TMP/hun-rejected.txt"
    verdicts native "$AFF" "$DIC" "$ENTRIES" | paste -d "$TAB" "$ENTRIES" - |
      awk -F'\t' '$2 == 0 { print $1 }' | sort > "$OUR_REJ"
    hunspell -d "$(hun_d "$DIC")" -l "$ENTRIES" 2>/dev/null | sort -u > "$HUN_REJ"
    OURS_ONLY="$(comm -23 "$OUR_REJ" "$HUN_REJ" | wc -l | tr -d ' ')"
    HUN_ONLY="$(comm -13 "$OUR_REJ" "$HUN_REJ" | wc -l | tr -d ' ')"
    echo "    ours rejects $(word_count "$OUR_REJ"), hunspell rejects $(word_count "$HUN_REJ")"
    if [ "$OURS_ONLY" = "0" ] && [ "$HUN_ONLY" = "0" ]; then
      echo "    the two agree exactly: both reject only $(tr '\n' ' ' < "$OUR_REJ")"
      echo "    (those carry ONLYINCOMPOUND and must be rejected standalone)"
    else
      echo "    disagreements: ours-only=$OURS_ONLY hunspell-only=$HUN_ONLY"
      comm -23 "$OUR_REJ" "$HUN_REJ" | sed 's/^/      ours rejects, hunspell accepts: /'
      comm -13 "$OUR_REJ" "$HUN_REJ" | sed 's/^/      hunspell rejects, ours accepts: /'
    fi
  fi

  # Cross-backend data point: the same big workload through the wasm backends.
  engine_words moon "$AFF" "$DIC" "$BIG" "$BIG_REPS"; MOON_BIG="$E_WORDS"
  engine_words moonrel "$AFF" "$DIC" "$BIG" "$BIG_REPS"; MOONREL_BIG="$E_WORDS"
  echo
  echo "  cross-backend reference on the same $BIG_N-word list (end-to-end, same .aff/.dic):"
  printf '    %-34s %10s s   %12s words/s\n' "native release" "$NAT_BIG" "$(f_wps "$BIG_N" "$NAT_BIG")"
  if [ -n "$MOONREL_BIG" ]; then
    printf '    %-34s %10s s   %12s words/s\n' "wasm release (\`moon run --release\`)" "$MOONREL_BIG" "$(f_wps "$BIG_N" "$MOONREL_BIG")"
  fi
  if [ -n "$MOON_BIG" ]; then
    printf '    %-34s %10s s   %12s words/s\n' "wasm debug (plain \`moon run\`)" "$MOON_BIG" "$(f_wps "$BIG_N" "$MOON_BIG")"
  fi
  echo "    (\`moon run\` builds DEBUG wasm by default; the release row shows what the"
  echo "     same backend does when compiled like the native binary.)"
  if [ -n "$MOONREL_BIG" ] && [ -n "$NAT_BIG" ]; then
    echo "  => native release is $(f_ratio "$MOONREL_BIG" "$NAT_BIG") faster than release wasm$([ -n "$MOON_BIG" ] && printf ' and %s faster than debug wasm' "$(f_ratio "$MOON_BIG" "$NAT_BIG")")"
  fi
  fi # end of the "native measurements succeeded" guard
fi

# -------------------------------------------------------- 4. scaling curve (synthetic)

section "4. scaling curve on SYNTHETIC dictionaries (native release)"
echo "Synthetic .aff/.dic pairs from bench/gen_dict.sh: 5 blocks / 8 rules, words are"
echo "base-20 syllable encodings. NOT real language data. The point is the SHAPE"
echo "across sizes: load grows with the entry count, the per-word cost must not."
echo "Every size is checked against the SAME $MEASURE_WORDS-word workload (the"
echo "dictionary's own entries, cycled when it is smaller), so the µs/word and"
echo "words/s columns are directly comparable down the column."
echo
if [ ! -x "$NATIVE" ]; then
  echo "SKIPPED: our native release executable was not built."
else
  # Determinism self-test: the generator must be byte-reproducible.
  DET_A="$TMP/determinism-a"; DET_B="$TMP/determinism-b"
  mkdir -p "$DET_A" "$DET_B"
  bash bench/gen_dict.sh 1000 "$DET_A" >/dev/null
  bash bench/gen_dict.sh 1000 "$DET_B" >/dev/null
  if [ "$(shasum -a 256 "$DET_A/synthetic.dic" | awk '{print $1}')" = "$(shasum -a 256 "$DET_B/synthetic.dic" | awk '{print $1}')" ]; then
    echo "generator determinism: OK (two 1,000-entry runs are byte-identical)"
  else
    echo "generator determinism: FAILED — the scaling numbers are not reproducible!" >&2
  fi
  echo
  engine_start native "$REPS_SMALL"; SYN_START="$E_START"
  if [ -z "$SYN_START" ]; then
    echo "ERROR: the process-start measurement failed; section 4 is skipped." >&2
  else
  printf '  %9s %10s %7s %10s %11s %11s %12s %12s\n' \
    "entries" "dic KiB" "rules" "load ms" "hit µs/w" "miss µs/w" "hit e2e w/s" "miss e2e w/s"
  printf '  %9s %10s %7s %10s %11s %11s %12s %12s\n' \
    "---------" "----------" "-------" "----------" "-----------" "-----------" "------------" "------------"
  for size in $SIZES; do
    dir="$TMP/synth/$size"
    mkdir -p "$dir"
    summary="$(bash bench/gen_dict.sh "$size" "$dir")"
    dic_bytes="$(printf '%s\n' "$summary" | sed -n 's/.*dic_bytes=\([0-9]*\).*/\1/p')"
    rules="$(printf '%s\n' "$summary" | sed -n 's/.*affix_rules=\([0-9]*\).*/\1/p')"
    awk -F/ -v want="$MEASURE_WORDS" '
      NR > 1 { w[++n] = $1 }
      END { for (i = 0; i < want; i++) print w[(i % n) + 1] }' "$dir/synthetic.dic" > "$dir/hits.txt"
    awk -F/ -v want="$MEASURE_WORDS" '
      NR > 1 { w[++n] = $1 }
      END { for (i = 0; i < want; i++) print w[(i % n) + 1] "xq" }' "$dir/synthetic.dic" > "$dir/misses.txt"
    # Small dictionary sizes still have a full-size workload, so the check phase
    # is always large compared with process-start jitter.
    if [ "$size" -lt 10000 ]; then reps="$REPS_SMALL"
    elif [ "$size" -lt "$HUGE_THRESHOLD" ]; then reps="$REPS_BIG"
    else reps="$REPS_HUGE"; fi
    engine_empty native "$dir/synthetic.aff" "$dir/synthetic.dic" "$REPS_SMALL"; syn_empty="$E_EMPTY"
    engine_words native "$dir/synthetic.aff" "$dir/synthetic.dic" "$dir/hits.txt" "$reps"; syn_hit="$E_WORDS"
    engine_words native "$dir/synthetic.aff" "$dir/synthetic.dic" "$dir/misses.txt" "$reps"; syn_miss="$E_WORDS"
    if [ -z "$syn_empty" ] || [ -z "$syn_hit" ] || [ -z "$syn_miss" ]; then
      echo "  $size: measurement failed" >&2
      continue
    fi
    syn_load="$(f_sub "$syn_empty" "$SYN_START")"
    syn_hit_only="$(f_sub "$syn_hit" "$syn_empty")"
    syn_miss_only="$(f_sub "$syn_miss" "$syn_empty")"
    printf '  %9s %10s %7s %10s %11s %11s %12s %12s\n' \
      "$size" \
      "$(awk -v b="$dic_bytes" 'BEGIN{printf "%.1f", b/1024}')" \
      "$rules" \
      "$(f_ms "$syn_load")" \
      "$(f_us "$syn_hit_only" "$MEASURE_WORDS")" \
      "$(f_us "$syn_miss_only" "$MEASURE_WORDS")" \
      "$(f_wps "$MEASURE_WORDS" "$syn_hit")" \
      "$(f_wps "$MEASURE_WORDS" "$syn_miss")"
    # Validity of the two word lists (hits accepted, misses rejected).
    h_acc="$(verdicts native "$dir/synthetic.aff" "$dir/synthetic.dic" "$dir/hits.txt" | grep -c '^1$' | tr -d ' ')"
    m_acc="$(verdicts native "$dir/synthetic.aff" "$dir/synthetic.dic" "$dir/misses.txt" | grep -c '^1$' | tr -d ' ')"
    if [ "$h_acc" != "$MEASURE_WORDS" ] || [ "$m_acc" != "0" ]; then
      echo "    WARNING: word-list validity off (hits accepted $h_acc/$MEASURE_WORDS, misses accepted $m_acc, expected 0)"
    fi
  done
  echo
  echo "  load = (empty-word-list run) - (no-arg run), both medians; it therefore"
  echo "  includes parsing + indexing but excludes process start. The µs/word columns"
  echo "  exclude start + load (the algorithm's own cost); the e2e words/s columns"
  echo "  include them (what a batch user sees). Both use the same $MEASURE_WORDS-word"
  echo "  workload at every size. Absolute values are machine-specific."
  echo "  The 8-rule synthetic affix set is smaller than real en_US ($RULE_LINES rules),"
  echo "  so synthetic miss cost is not comparable to section 3 in absolute terms —"
  echo "  the trend across sizes is the result."
  fi # end of the "SYN_START measured" guard
fi

# ------------------------------------------------------------------ 5. artifact size

section "5. release artifact size"
artifact() { # <label> <path>
  if [ -f "$2" ]; then
    printf '  %-9s %12s bytes   %s\n' "$1" "$(wc -c < "$2" | tr -d ' ')" "$2"
  else
    printf '  %-9s %12s         %s\n' "$1" "missing" "$2"
  fi
}
echo "  built with \`moon build --release\`; these are the executable payloads of the"
echo "  CLI package (cmd/main). Libraries ship as source + generated .mbti interfaces."
echo
artifact wasm "$WASM_ART"
artifact wasm-gc "$WASMGC_ART"
artifact js "$JS_ART"
artifact native "$NATIVE"
echo
if [ -f "$WASM_ART" ]; then
  TOTAL_KB="$(awk -v b="$(wc -c < "$WASM_ART" | tr -d ' ')" 'BEGIN{printf "%.1f", b/1024}')"
  echo "  the wasm CLI release artifact is ${TOTAL_KB} KiB — the payload a wasm host"
  echo "  (browser, edge worker, WASI) downloads and runs, with no C++ runtime."
fi

# ----------------------------------------------------------------------- summary

section "done"
echo "Every number above was measured by this script. Absolute values are"
echo "machine-specific; medians over $REPS_SMALL/$REPS_BIG/$REPS_HUGE repetitions."
echo "Reproduce with:  bash bench/run.sh"
echo "Method, caveats and deliberately-absent comparisons: bench/README.md"
if [ "$CLEANUP" = "0" ]; then echo "Temp dir kept at: $TMP"; fi
exit 0
